### ISSUE TITLE
Create DACODS Questionnaire (SDC) custom value sets and code systems

### ISSUE THREAD

**Issue by enjoysparkling** [jfabrizio329/signal-mso-fhir-profiles#108]
As an implementer I need [answerValueSet](http://hl7.org/fhir/R4/questionnaire-definitions.html#Questionnaire.item.answerValueSet) to be created for "choice questions".

---

Tasks:

- [x] Identify best way to incorporate answerValueSet
- [x] Identify value sets, match to existing if possible
- [ ] Create additional value sets
- Survey valuesets... 
   - [ ] Add a section in Terminology ([Questionnaire Terminology](https://simplifier.net/guide/signal-implementation-guide/index/terminology/questionnaire-terminology.page.md?version=current))

**Comment by arunsundar-m** [comment]
@enjoysparkling I have identified the value sets from Admission DACODS user manual

S No | Item | Valueset Names
-- | -- | --
1 | SSPA Number | valueset-questionnaire-admission-sspa-number
2 | ReportType | valueset-questionnaire-admission-report-type
3 | County | valueset-address-fips-county-colorado.json
4 | Admission Modality | valueset-questionnaire-admission-modality
5 | Gender | valueset-gender.json
6 | sexual orientation | valueset-questionnaire-admission-sexual-orientation
7 | Race | Reuse, we need to add   Declined as additional
8 | Ethnicity | Reuse, we need to add   custom values/Declined as additional
9 | marital-status | Need to expand the   existing valueset
10 | living situation | valueset-questionnaire-admission-living-situation
11 | disability status | valueset-questionnaire-admission-disability-status
12 | Education Level | valueset-questionnaire-admission-education-level
13 | Employment Status | valueset-questionnaire-admission-employment-status
14 | Transfer or referral source | valueset-questionnaire-admission-transfer-referral-source
15 | family_issues_problems | valueset-questionnaire-admission-family-issues-and-problems
16 | socialization-problems | valueset-questionnaire-admission-socialization-problems
17 | education-employment-problems | valueset-questionnaire-admission-education-employment-problems
18 | medical-physical-problems | valueset-questionnaire-admission-medical-physical-problems
19 | clinician-diagnostic-impression | valueset-questionnaire-admission-clinician-diagnostic-impression
20 | route-of-administration | valueset-questionnaire-admission-route-of-administration
21 | source-of-illicit-drugs | valueset-questionnaire-admission-source-of-illicit-drugs
22 | tobacco-use | valueset-questionnaire-admission-toabacco-use
23 | statutory-commitment | valueset-questionnaire-admission-statutory-commitment
24 | health-insurance-status | valueset-questionnaire-admission-health-insurance-status
25 | source-of-income | valueset-questionnaire-admission-source-of-income
26 | source-of-payment-for-treatment | valueset-questionnaire-admission-source-of-payment-for-treatment
27 | drug-type | valueset-questionnaire-admission-drug-type
28 | Yes or No | Need to form a new   valueset using the existing code system

**Comment by arunsundar-m** [comment]
@Gokulsignal Please start creating the value sets as per the attached sheet.

[Admission_Valueset_Details.xlsx](https://github.com/enjoysparkling/signal-mso-fhir-profiles/files/12830702/Admission_Valueset_Details.xlsx)

**Comment by enjoysparkling** [comment]
We will determine what DACODS questions a provider needs to answer by using Appendix A (Version 6) from
[Signal File Format and Survey Specification V2.4.pdf](https://sbhn.sharepoint.com/sites/ITModernization/Shared%20Documents/Collateral/SpecDocuments/Signal%20File%20Format%20and%20Survey%20Specification%20V2.4.pdf?csf=1&web=1&e=8kKAs5)
(per Joe H).

**Comment by enjoysparkling** [comment]
@arunsundar-m - Would you research and share the following elements for the Questionnaire:
- the manual DACODS Version (e.g. version 6) 
- Question Export Number (the manual numbering, based on the reporting out of DACODS).
- The Question Base ID, which is the number on the form (is it item.id??)

**Comment by arunsundar-m** [comment]
@enjoysparkling 

Hi Matt, Please find the elements that we can use for the below information.

the manual DACODS Version (e.g. version 6) - **_Questionnaire.version_**
Question Export Number (the manual numbering, based on the reporting out of DACODS) - **_Questionnaire.item,prefix_** I feel we can use this label for storing the export number Signal uses it for reporting.
The Question Base ID, which is the number on the form (is it item.id??) - **_Questionnaire.item.linkId_**

**Comment by enjoysparkling** [comment]
Reminder: Use the [Structure Data Capture](http://hl7.org/fhir/uv/sdc/STU3/index.html) (SDC) resource profiles for Questionnaire, ValueSet, CodeSystem.  QuestionnaireResponse will be the US Core profile (based off the SDC)
