### ISSUE TITLE
Add Place of Service (POS) CMS code to Location.type valueset

### ISSUE THREAD

**Issue by enjoysparkling** [jfabrizio329/signal-mso-fhir-profiles#126]
As an implementer I want to be able to capture the [Place of Service](https://www.cms.gov/medicare/coding-billing/place-of-service-codes/code-sets) on an encounter that specifies where services were encountered for billing coding.

See #76 - I am not sure how this got skipped, but it's that task below.

---

Task:
Edit the Signal Location Profile
- [ ] Location.type - we might need to repurpose this for Place of Service (POS)
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/50, [input/vocabulary/valueset-service-delivery-location-role-type.json](https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/50/files/d7459314fedfdf6e4240791f0e866d275643268d#diff-cbee1cd4f5cc4d7c0d08f7674fadb56b24a456b58fe9e6bdd6c09426b76124b5)
   - Add codes for [Place of Service](https://www.cms.gov/medicare/coding-billing/place-of-service-codes/code-sets)
   - Confirm codes match the [USCS Manual](https://hcpf.colorado.gov/sites/hcpf/files/July%202023%20USCS%20Manual%20Draft%20-Final.pdf).  
   - use https://www.hl7.org/fhir/valueset-service-place.html if possible.  If necessary, create a new code system with complete code set.
  - [ ] Bind the new valueset to Location.type

**Comment by arunsundar-m** [comment]
@Gokulsignal 

1. Use http://terminology.hl7.org/CodeSystem/ex-serviceplace and change the new code system that you have created just by excluding the ones in this code system.
2. Edit the valueset including the codesystem http://terminology.hl7.org/CodeSystem/ex-serviceplace

**Comment by Gokulsignal** [comment]
The below changes are completed:

1. The new code system is updated by excluding the concepts available in this code system http://terminology.hl7.org/CodeSystem/ex-serviceplace.
2. The valueset are updated including the codesystem http://terminology.hl7.org/CodeSystem/ex-serviceplace.

Kindly review @enjoysparkling

**Comment by enjoysparkling** [comment]
FYI - I submitted a request with HL7 to update their code system with the latest codes:  https://jira.hl7.org/browse/FHIR-43059
