### ISSUE TITLE
Create an Encounter "Attempt to Contact" profile

### ISSUE THREAD

**Issue by enjoysparkling** [jfabrizio329/signal-mso-fhir-profiles#128]
As an implementer I want a template profile for a pre-admission encounter that is part of the referral "Attempt to contact" workflow.

Business context:
- A referral is generated and associated resources created in FHIR (see components below).
- A Care Manager will reach out to the member to notify them of the referral with details; this is an "Attempt to contact". 
- Attempt to contact encounters will often be the first interaction between a patient/client and their care.

Components needed as part of the referral workflow:
- ServiceRequest resource (referral)
- EpisodeOfCare (admission) - with Referral link and required fields
- Encounter Attempt to Contact  

---

Tasks:
- [ ] Collect business requirements, elements and values needed to populate Encounter
- [ ] Take our current Encounter profile as the baseDefinition and modify it to have pre-populated sections for a virtual "Attempt to contact" 
   - Call it "Encounter referral attempt to contact"
- [ ] Document in IG

**Comment by enjoysparkling** [comment]
Will also need a result from this that will represent the "Contact Attempt Results"; e.g. "Got a hold of customer", "Left a voicemail", "Did not contact"...  
Suggestions:
- Observation (??)

**Comment by arunsundar-m** [comment]
![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/124249650/5bf55b93-35a7-45e0-8fbb-bfae82daafbf)

**Comment by enjoysparkling** [comment]
Outstanding Tasks
- [ ] Get CPT/SNOMED code for `Encounter.type` that represents the "attempt to contact"
- [ ] Create the Observation and get the code for the "Contact Attempt Results"

**Comment by arunsundar-m** [comment]
Task resource has been identified as a replacement for Encounter resource to fulfill the requirements.
