### ISSUE TITLE
Create an Encounter survey profile.

### ISSUE THREAD

**Issue by enjoysparkling** [jfabrizio329/signal-mso-fhir-profiles#133]
As an implementer I want a template profile for any type of survey that is collected in the workflow.

Business context:
- Developers want a pre-filled template to make it easier to create a survey event

Components needed as part of the survey workflow:
- Pre-populate reasonReference, Procedure, and/or other fields to describe encounter as a "survey event"
- Link survey-related resources: Questionnaire and QuestionnaireResponse 
- ... Others(??)

**Comment by arunsundar-m** [comment]
The analysis of creating an encounter survey profile for admission/discharge survey is completed. Encounter.type will be 'admission-survey' or 'discharge-survey'. The rest of the fields can be populated as is for an encounter with a procedure code. The status column can be changed accordingly when it is created as 'arrived' and when the survey is submitted, it can be marked as 'finished'.
